import Head from "next/head";
import { Inter } from "@next/font/google";
import HeroSection from "components/HeroSection";
import Services from "components/Services";
import Testimonial from "components/Testimonial";
import { useEffect } from "react";
import ContactUs from "components/ContactUs";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Medicreative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-16">
        <HeroSection />
        <Services />
        <Testimonial />
        <ContactUs />
      </main>
    </>
  );
}
